name: Docker Image CI & Push

on:
  workflow_dispatch:  # 手动触发

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract branch name
        id: vars
        run: echo "BRANCH_NAME=${GITHUB_REF_NAME}" >> $GITHUB_ENV

      - name: Build and push
        working-directory: ./
        run: |
          IMAGE_NAME=lianshufeng/label-studio-zh:${BRANCH_NAME}
          echo "Using tag: $IMAGE_NAME"

          docker build -f Dockerfile -t $IMAGE_NAME .
          docker push $IMAGE_NAME


      - name: Build and push
        working-directory: ./
        run: |
          IMAGE_NAME=lianshufeng/label-studio-zh:latest
          echo "Using tag: $IMAGE_NAME"

          docker build -f Dockerfile -t $IMAGE_NAME .
          docker push $IMAGE_NAME
